//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6Poligon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdPoligonsEntities : DbContext
    {
        public bdPoligonsEntities()
            : base("name=bdPoligonsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbCercle> tbCercle { get; set; }
        public virtual DbSet<tbElipse> tbElipse { get; set; }
        public virtual DbSet<tbHexagons> tbHexagons { get; set; }
        public virtual DbSet<tbOctagons> tbOctagons { get; set; }
        public virtual DbSet<tbPentagons> tbPentagons { get; set; }
        public virtual DbSet<tbPoligons> tbPoligons { get; set; }
        public virtual DbSet<tbQuadrat> tbQuadrat { get; set; }
        public virtual DbSet<tbRectangle> tbRectangle { get; set; }
        public virtual DbSet<tbRombes> tbRombes { get; set; }
        public virtual DbSet<tbTriangleIsosceles> tbTriangleIsosceles { get; set; }
        public virtual DbSet<tbTriangleRectangle> tbTriangleRectangle { get; set; }
    }
}
