//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6Poligon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbElipse
    {
        public int idElipse { get; set; }
        public Nullable<int> idPoligon { get; set; }
        public Nullable<int> x { get; set; }
        public Nullable<int> y { get; set; }
    
        public virtual tbPoligons tbPoligons { get; set; }
    }
}
