//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M6Poligon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPoligons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPoligons()
        {
            this.tbCercle = new HashSet<tbCercle>();
            this.tbElipse = new HashSet<tbElipse>();
            this.tbHexagons = new HashSet<tbHexagons>();
            this.tbOctagons = new HashSet<tbOctagons>();
            this.tbPentagons = new HashSet<tbPentagons>();
            this.tbQuadrat = new HashSet<tbQuadrat>();
            this.tbRectangle = new HashSet<tbRectangle>();
            this.tbRombes = new HashSet<tbRombes>();
            this.tbTriangleRectangle = new HashSet<tbTriangleRectangle>();
            this.tbTriangleIsosceles = new HashSet<tbTriangleIsosceles>();
        }
    
        public int idPoligon { get; set; }
        public string nombre { get; set; }
        public string color { get; set; }
        public string forma { get; set; }
        public Nullable<bool> ple { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCercle> tbCercle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbElipse> tbElipse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHexagons> tbHexagons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbOctagons> tbOctagons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPentagons> tbPentagons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbQuadrat> tbQuadrat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRectangle> tbRectangle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRombes> tbRombes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTriangleRectangle> tbTriangleRectangle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTriangleIsosceles> tbTriangleIsosceles { get; set; }
    }
}
